package skill.events;

public enum EventType {
    //Function<Game,boolean>
    GAME_START,
    //Function<Player,boolean>
    TURN_START,
    //Function<Phase,boolean>
    PHASE_START,
    PHASE_PROCEEDING,
    PHASE_END,
    PHASE_CHANGING,
    PHASE_SKIPPING,

    DRAW_CARD,

    BEFORE_HP_RECOVER,
    AFTER_HP_RECOVER,
    BEFORE_HP_LOST,
    AFTER_HP_LOST,

    HP_CHANGED,
    MAX_HP_CHANGED,

    EVENT_LOSE_SKILL,
    EVENT_NEED_SKILL,

    BEFORE_JUDGE,
    AFTER_JUDGE,

    BEFORE_RACE_CARD,
    BY_RACE_CARD,
    AFTER_RACE_CARD,




    CONFIRM_DAMAGE,
    DAMAGE_FORESEEN,
    DAMAGE_CAUSED,
    DAMAGE_INFLICTED,
    BEFORE_DAMAGE_DONE,
    DAMAGE_DONE,
    DAMAGE,
    DAMAGED,
    DAMAGE_COMPLETE,


    ATTACKEFFECTED,
    ATTACKPROCEED,
    ATTACKHIT,
    ATTACKMISSED,

    CARD_ASKED,
    CARD_RESPONDED,
    BEFORE_CARD_MOVE,
    AFTER_CARD_MOVE,

    BEFORE_CARD_USE,
    CARD_USED,
    TARGET_CONFIRMING,
    TARGET_CONFIRMED;

    /*
    *optional for future
    CHAIN_STATE_CHANGE,
    DYING,
    ASKFORHEAL,
    ASKFORHEALDONE,
    DEATH,
    CARD_EFFECT,
    CARD_EFFECTED,
    AFTER_CARD_EFFECTED
    */




}